{% set version = "0.10.0" %}

package:
  name: qtkeychain
  version: {{ version }}

source:
  url: https://github.com/frankosterfeld/qtkeychain/archive/v{{ version }}.tar.gz
  sha256: 5f916cd97843de550467db32d2e10f218b904af5b21cfdfcc7c6425d7dfc3ec2
  patches:
    - enable_language.patch

build:
  skip: True  # [win and vc<14]
  number: 0

requirements:
  build:
    - pkg-config  # [unix]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - qt
  run:
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libqt5keychain${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_BIN%\\qt5keychain.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\qt5keychain.lib exit 1  # [win]

about:
  home: https://github.com/frankosterfeld/qtkeychain
  license: BSD-3-Clause
  license_file: COPYING
  summary: 'QtKeychain is a Qt API to store passwords and other secret data securely'

extra:
  recipe-maintainers:
    - ceholden
    - gillins
