{% set version = "0.11.1" %}

package:
  name: qtkeychain
  version: {{ version }}

source:
  url: https://github.com/frankosterfeld/qtkeychain/archive/v{{ version }}.tar.gz
  sha256: 77fc6841c1743d9e6bd499989481cd9239c21bc9bf0760d41a4f4068d2f0a49d
  patches:
    - enable_language.patch

build:
  skip: true  # [win and vc<14]
  number: 0

requirements:
  build:
    - pkg-config  # [unix]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - qt
  run:
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libqt5keychain${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_BIN%\\qt5keychain.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\qt5keychain.lib exit 1  # [win]

about:
  home: https://github.com/frankosterfeld/qtkeychain
  license: BSD-3-Clause
  license_file: COPYING
  summary: QtKeychain is a Qt API to store passwords and other secret data securely

extra:
  recipe-maintainers:
    - ceholden
    - gillins
