travis:
  secure:
    BINSTAR_TOKEN: eEmbmXFjLMPyhNjRlA3uH8iJaoodPXmI5g6DDmAKHQJyi9kcqCdh4QwwcgCylZ7vCw2juMmEk5raR/NNlR9e+PYOOAEcTgXveinjxOf+/fc2ShVsTCKf93SuzO0A8zqc8pZJKw8GquSM0qnrg84DzrC0fCMfDwJmQhTucrwq4UgPfsAfDjVBPAzOFz0wp9RYwie4a2H4Cvu/L1u7aGE/xzBBBUgjIImcvIIwFk8wDuo7SkmLh8UCUrrdMfuibt8rIx82XggkLZfdGUDqF1uq+JUk9PXSbe9gXfSbRDhwubidRFXK/mgIp59l3tf/JMMh3Aznjqub0hfb0SJW7g/4BclGcl0tj9eZ+GIgRqtO4abOqZqd1O+EQ8FeExLaAQC/nb2i67k5HeS9WYzzRuU0ghDOAY1aDUXgdKD7JMvm3y9DtFMm8OGZTyaizlOXp9xXVeptE3k927fLsByBq/jvmiF/KErrtdUmCfqg0KH4GOvs0tgdoZtQejIzhJxv1ZYVBEXoC/4cu6ZPjkHV7MZEDt7f44fXUoa+soi85FTx7GKsdOIpjRrGSxUVcewrbrsZJpJfUXMHf9uU8LTSFAp9K6p9GQ60AYxDnAsQEn3OtliKYw5z7JJUbnkyD2MKjywDDw3QeGBKgbtgqu3e7OEaUb30E8m1NXc3ZlCKFmHzJmU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
